const path=require('path')
console.log(path.extname('./app.js'))
console.log(path.dirname('./temp/utility.js'))
console.log(__dirname)
console.log(path.join(__dirname,'./app.js'))
console.log(path.resolve('./app.js'))
